### ISSUE TITLE
DeriveNoise实现

### ISSUE THREAD

**Issue by akidongzi** [cunicu/hawkes#76]
// Derive a shared secret using the input public key against the private key that was found during setup.
// Returns a fixed 32 byte array.
func (c *PKClient) DeriveNoise(peerPubKey [NoisePublicKeySize]byte) (secret [NoisePrivateKeySize]byte, err error) {
	if !c.HSMSession.loggedIn {
		return secret, errLogin
	}

	var mechMech uint = pkcs11.CKM_ECDH1_DERIVE

	// Before we call derive, we need to have an array of attributes which specify the type of
	// key to be returned, in our case, it's the shared secret key, produced via deriving
	// This template pulled from OpenSC pkcs11-tool.c line 4038
	attrTemplate := []*pkcs11.Attribute{
		pkcs11.NewAttribute(pkcs11.CKA_TOKEN, false),
		pkcs11.NewAttribute(pkcs11.CKA_CLASS, pkcs11.CKO_SECRET_KEY),
		pkcs11.NewAttribute(pkcs11.CKA_KEY_TYPE, pkcs11.CKK_GENERIC_SECRET),
		pkcs11.NewAttribute(pkcs11.CKA_SENSITIVE, false),
		pkcs11.NewAttribute(pkcs11.CKA_EXTRACTABLE, true),
		pkcs11.NewAttribute(pkcs11.CKA_ENCRYPT, true),
		pkcs11.NewAttribute(pkcs11.CKA_DECRYPT, true),
		pkcs11.NewAttribute(pkcs11.CKA_WRAP, true),
		pkcs11.NewAttribute(pkcs11.CKA_UNWRAP, true),
	}

	// Setup the parameters which include the peer's public key
	ecdhParams := pkcs11.NewECDH1DeriveParams(pkcs11.CKD_NULL, nil, peerPubKey[:NoisePublicKeySize])

	mech := pkcs11.NewMechanism(mechMech, ecdhParams)

	// Derive the secret key from the public key as input and the private key on the device
	sk := p11.PrivateKey(c.HSMSession.privKeyObj)
	tmpKey, err := sk.Derive(*mech, attrTemplate)
	if err != nil {
		return secret, err
	}

	copy(secret[:], tmpKey[:NoisePrivateKeySize])
	return secret, err
}  这个方法有测试数据没

**Comment by stv0g** [comment]
没有

**Comment by akidongzi** [comment]
这个方法无法生成了，我测试了
